function shop_init(){
	register_goods("large_fire",{"type":"card","cost":"10000","unlock_item_id":"large_fire","description":"大火炉：一次生产两朵火苗","display_name":"大火炉"})
	register_goods("iron_fishbone",{"type":"card","cost":"5000","unlock_item_id":"iron_fishbone","description":"钢鱼刺：攻击踩上它的老鼠，卡坏四次垃圾车","display_name":"钢鱼刺"})
	register_goods("gatlin_long_bao",{"type":"card","cost":"50000","unlock_item_id":"gatlin_long_bao","description":"机枪小笼包：发射四发包子","display_name":"机枪小笼包"})
	register_goods("rotating_coffee_pot",{"type":"card","cost":"50000","unlock_item_id":"rotating_coffee_pot","description":"旋转咖啡喷壶：3*3范围穿透攻击，白天睡觉","display_name":"旋转咖啡喷壶"})
	register_goods("takoyaki",{"type":"card","cost":"80000","unlock_item_id":"takoyaki","description":"章鱼烧：甩出两发追踪飞镖","display_name":"章鱼烧"})
	register_goods("ice_egg_boiler_pult",{"type":"card","cost":"30000","unlock_item_id":"ice_egg_boiler_pult","description":"冰煮蛋器：投掷减速冰鸡蛋","display_name":"冰煮蛋器"})
	register_goods("chocolate_cannon",{"type":"card","cost":"80000","unlock_item_id":"chocolate_cannon","description":"巧克力大炮：发射3*3范围爆炸的巧克力球","display_name":"巧克力大炮"})
	
	register_goods("card_slot_plus",{"type":"item","cost":"20000","unlock_item_id":"card_slot","description":"增加一格卡槽，仅可在卡槽数小于18时使用","display_name":"卡槽+1","spr":spr_slot_plus})
	register_goods("card_slot_19",{"type":"item","cost":"50000","unlock_item_id":"card_slot_19","description":"解锁第19格卡槽","display_name":"卡槽第19格","spr":spr_slot_19})
	register_goods("card_slot_20",{"type":"item","cost":"80000","unlock_item_id":"card_slot_20","description":"解锁第20格卡槽","display_name":"卡槽第20格","spr":spr_slot_20})
	register_goods("card_slot_21",{"type":"item","cost":"100000","unlock_item_id":"card_slot_21","description":"解锁第21格卡槽","display_name":"卡槽第21格","spr":spr_slot_21})
	
	register_goods("howitzer",{"type":"weapon","cost":"20000","unlock_item_id":"howitzer","description":"榴弹炮：自动发射高伤害榴弹","display_name":"榴弹炮"})
	register_goods("enhanced_howitzer",{"type":"weapon","cost":"50000","unlock_item_id":"enhanced_howitzer","description":"加强榴弹炮：自动发射两个高伤害榴弹","display_name":"加强榴弹炮"})
	register_goods("mighty_gun",{"type":"weapon","cost":"15000","unlock_item_id":"mighty_gun","description":"威武枪：发射四发子弹","display_name":"威武枪"})
	register_goods("cat_gun",{"type":"weapon","cost":"50000","unlock_item_id":"cat_gun","description":"猫猫枪：发射能惊吓敌人的猫猫弹","display_name":"猫猫枪"})
	register_goods("cut_cake_shield",{"type":"weapon","cost":"8000","unlock_item_id":"cut_cake_shield","description":"切糕盾牌：增加300生命值","display_name":"切糕盾牌"})
	register_goods("starlight_gem",{"type":"gem","cost":"30000","unlock_item_id":"starlight_gem","description":"星光宝石：召唤星星压扁老鼠并产生火苗","display_name":"星光宝石"})
	register_goods("flame_recover_gem",{"type":"gem","cost":"50000","unlock_item_id":"flame_recover_gem","description":"回火宝石：从天上掉落火苗","display_name":"回火宝石"})
	register_goods("power_gem",{"type":"gem","cost":"15000","unlock_item_id":"power_gem","description":"强力宝石：增加超级武器伤害","display_name":"强力宝石"})
	register_goods("gale_gem",{"type":"gem","cost":"50000","unlock_item_id":"gale_gem","description":"疾风宝石：增加超级武器攻速","display_name":"疾风宝石"})
	register_goods("transform_gem",{"type":"gem","cost":"50000","unlock_item_id":"transform_gem","description":"转化宝石：子弹落地产生火苗","display_name":"转化宝石"})
	register_goods("bleed_gem",{"type":"gem","cost":"20000","unlock_item_id":"bleed_gem","description":"流血宝石：伤害周围敌人","display_name":"流血宝石"})
	register_goods("guard_gem",{"type":"gem","cost":"20000","unlock_item_id":"guard_gem","description":"守护宝石：治疗周围卡片并增加生命上限","display_name":"守护宝石"})
	register_goods("strength_gem",{"type":"gem","cost":"50000","unlock_item_id":"strength_gem","description":"蓄力宝石：增加周围卡片伤害","display_name":"蓄力宝石"})
	register_goods("ice_spoon_crossbow",{"type":"weapon","cost":"20000","unlock_item_id":"ice_spoon_crossbow","description":"冰勺弩枪：投掷减速冰鸡蛋","display_name":"冰勺弩枪"})
}