function maps_init(){
	map_registry_init()
	register_map("delicious_island",{"map_name":"美味岛","map_sprite":spr_delicious_islands,"levels_data":[{"id":"salad_island_land","name":"色拉岛（陆）","button_spr":spr_levelselect_button,"button_index":1,"button_x":1365,"button_y":455,"level_file":"salad_island_land.json","level_sprite":spr_salad_island_land,"pre_music":mus_delicious_island_daytime_pre,"elite_music":mus_delicious_island_daytime_elite,"boss_music":mus_delicious_island_daytime_boss},
																										{"id":"salad_island_water","name":"色拉岛（水）","button_spr":spr_levelselect_button,"button_index":2,"button_x":1395,"button_y":620,"level_file":"salad_island_water.json","level_sprite":spr_salad_island_water,"pre_music":mus_delicious_island_daytime_pre,"elite_music":mus_delicious_island_daytime_elite,"boss_music":mus_delicious_island_daytime_boss},
																										{"id":"cookie_island","name":"曲奇岛","button_spr":spr_levelselect_button,"button_index":0,"button_x":1295,"button_y":285,"level_file":"cookie_island.json","level_sprite":spr_cookie_island,"pre_music":mus_delicious_island_daytime_pre,"elite_music":mus_delicious_island_daytime_elite,"boss_music":mus_delicious_island_daytime_boss},
																										{"id":"mousse_island","name":"慕斯岛","button_spr":spr_levelselect_button,"button_index":3,"button_x":1310,"button_y":730,"level_file":"mousse_island.json","level_sprite":spr_mousse_island,"pre_music":mus_delicious_island_night_pre,"elite_music":mus_delicious_island_night_elite,"boss_music":mus_delicious_island_night_boss},
																										{"id":"champagne_island_land","name":"香槟岛（陆）","button_spr":spr_levelselect_button,"button_index":4,"button_x":1070,"button_y":833,"level_file":"champagne_island_land.json","level_sprite":spr_champagne_island_land,"pre_music":mus_delicious_island_night_pre,"elite_music":mus_delicious_island_night_elite,"boss_music":mus_delicious_island_night_boss},
																										{"id":"champagne_island_water","name":"香槟岛（水）","button_spr":spr_levelselect_button,"button_index":5,"button_x":885,"button_y":765,"level_file":"champagne_island_water.json","level_sprite":spr_champagne_island_water,"pre_music":mus_delicious_island_night_pre,"elite_music":mus_delicious_island_night_elite,"boss_music":mus_delicious_island_night_boss},
																										{"id":"temple","name":"神殿","button_spr":spr_levelselect_button,"button_index":6,"button_x":630,"button_y":720,"level_file":"temple.json","level_sprite":spr_temple,"pre_music":mus_delicious_island_crown_pre,"elite_music":mus_delicious_island_crown_elite,"boss_music":mus_delicious_island_night_boss},
	]})
}