function maps_init(){
	map_registry_init()
	register_map("delicious_island",{"map_name":"美味岛","map_sprite":spr_delicious_islands,"levels_data":[{"id":"salad_island_land","name":"色拉岛（陆）","button_spr":spr_levelselect_button,"button_index":1,"button_x":1365,"button_y":455,"level_file":"salad_island_land.json","hard_level_file":"salad_island_land_hard.json","level_sprite":spr_salad_island_land,"pre_music":mus_delicious_island_daytime_pre,"elite_music":mus_delicious_island_daytime_elite,"boss_music":mus_delicious_island_daytime_boss,"player_level_require":2,"pre_level_require":[]},
																										{"id":"salad_island_water","name":"色拉岛（水）","button_spr":spr_levelselect_button,"button_index":2,"button_x":1395,"button_y":620,"level_file":"salad_island_water.json","hard_level_file":"salad_island_water_hard.json","level_sprite":spr_salad_island_water,"pre_music":mus_delicious_island_daytime_pre,"elite_music":mus_delicious_island_daytime_elite,"boss_music":mus_delicious_island_daytime_boss,"player_level_require":3,"pre_level_require":[]},
																										{"id":"cookie_island","name":"曲奇岛","button_spr":spr_levelselect_button,"button_index":0,"button_x":1295,"button_y":285,"level_file":"cookie_island.json","hard_level_file":"cookie_island_hard.json","level_sprite":spr_cookie_island,"pre_music":mus_delicious_island_daytime_pre,"elite_music":mus_delicious_island_daytime_elite,"boss_music":mus_delicious_island_daytime_boss,"player_level_require":1,"pre_level_require":[]},
																										{"id":"mousse_island","name":"慕斯岛","button_spr":spr_levelselect_button,"button_index":3,"button_x":1310,"button_y":730,"level_file":"mousse_island.json","hard_level_file":"mousse_island_hard.json","level_sprite":spr_mousse_island,"pre_music":mus_delicious_island_night_pre,"elite_music":mus_delicious_island_night_elite,"boss_music":mus_delicious_island_night_boss,"player_level_require":4,"pre_level_require":[]},
																										{"id":"champagne_island_land","name":"香槟岛（陆）","button_spr":spr_levelselect_button,"button_index":4,"button_x":1070,"button_y":833,"level_file":"champagne_island_land.json","hard_level_file":"champagne_island_land_hard.json","level_sprite":spr_champagne_island_land,"pre_music":mus_delicious_island_night_pre,"elite_music":mus_delicious_island_night_elite,"boss_music":mus_delicious_island_night_boss,"player_level_require":5,"pre_level_require":[]},
																										{"id":"champagne_island_water","name":"香槟岛（水）","button_spr":spr_levelselect_button,"button_index":5,"button_x":885,"button_y":765,"level_file":"champagne_island_water.json","hard_level_file":"champagne_island_water_hard.json","level_sprite":spr_champagne_island_water,"pre_music":mus_delicious_island_night_pre,"elite_music":mus_delicious_island_night_elite,"boss_music":mus_delicious_island_night_boss,"player_level_require":6,"pre_level_require":[]},
																										{"id":"temple","name":"神殿","button_spr":spr_levelselect_button,"button_index":6,"button_x":630,"button_y":720,"level_file":"temple.json","hard_level_file":"temple_hard.json","level_sprite":spr_temple,"pre_music":mus_delicious_island_crown_pre,"elite_music":mus_delicious_island_crown_elite,"boss_music":mus_delicious_island_night_boss,"player_level_require":7,"pre_level_require":[]},
																										{"id":"pudding_island_daytime","name":"布丁岛（日）","button_spr":spr_levelselect_button,"button_index":7,"button_x":405,"button_y":715,"level_file":"pudding_island_daytime.json","hard_level_file":"pudding_island_daytime_hard.json","level_sprite":spr_pudding_island_daytime,"pre_music":mus_delicious_island_daytime_pre,"elite_music":mus_delicious_island_daytime_elite,"boss_music":mus_delicious_island_daytime_boss,"player_level_require":9,"pre_level_require":[]},
																										{"id":"pudding_island_night","name":"布丁岛（夜）","button_spr":spr_levelselect_button,"button_index":8,"button_x":285,"button_y":585,"level_file":"pudding_island_night.json","hard_level_file":"pudding_island_night_hard.json","level_sprite":spr_pudding_island_night,"pre_music":mus_delicious_island_night_pre,"elite_music":mus_delicious_island_night_elite,"boss_music":mus_delicious_island_night_boss,"player_level_require":10,"pre_level_require":[]},
																										{"id":"cocoa_island_daytime","name":"可可岛（日）","button_spr":spr_levelselect_button,"button_index":9,"button_x":335,"button_y":475,"level_file":"cocoa_island_daytime.json","hard_level_file":"cocoa_island_daytime_hard.json","level_sprite":spr_cocoa_island_daytime,"pre_music":mus_delicious_island_daytime_pre,"elite_music":mus_delicious_island_daytime_elite,"boss_music":mus_delicious_island_daytime_boss,"player_level_require":11,"pre_level_require":[]},
																										{"id":"cocoa_island_night","name":"可可岛（夜）","button_spr":spr_levelselect_button,"button_index":10,"button_x":375,"button_y":365,"level_file":"cocoa_island_night.json","hard_level_file":"cocoa_island_night_hard.json","level_sprite":spr_cocoa_island_night,"pre_music":mus_delicious_island_night_pre,"elite_music":mus_delicious_island_night_elite,"boss_music":mus_delicious_island_night_boss,"player_level_require":12,"pre_level_require":[]},
																										{"id":"curry_island_daytime","name":"咖喱岛（日）","button_spr":spr_levelselect_button,"button_index":11,"button_x":455,"button_y":255,"level_file":"curry_island_daytime.json","hard_level_file":"curry_island_daytime_hard.json","level_sprite":spr_curry_island_daytime,"pre_music":mus_delicious_island_daytime_pre,"elite_music":mus_delicious_island_daytime_elite,"boss_music":mus_delicious_island_daytime_boss,"player_level_require":13,"pre_level_require":[]},
																										{"id":"curry_island_night","name":"咖喱岛（夜）","button_spr":spr_levelselect_button,"button_index":12,"button_x":578,"button_y":215,"level_file":"curry_island_night.json","hard_level_file":"curry_island_night_hard.json","level_sprite":spr_curry_island_night,"pre_music":mus_delicious_island_night_pre,"elite_music":mus_delicious_island_night_elite,"boss_music":mus_delicious_island_night_boss,"player_level_require":14,"pre_level_require":[]},
																										{"id":"abyss","name":"深渊岛","button_spr":spr_levelselect_button,"button_index":13,"button_x":750,"button_y":135,"level_file":"abyss.json","hard_level_file":"abyss_hard.json","level_sprite":spr_abyss,"pre_music":mus_delicious_island_crown_pre,"elite_music":mus_delicious_island_crown_elite,"boss_music":mus_delicious_island_daytime_boss,"player_level_require":15,"pre_level_require":[]},
	]})
}