instance_destroy(obj_closetowercake_btn)
instance_destroy(obj_tower_cake_page_btn)
instance_destroy(obj_tower_cake_start_btn)
instance_destroy(obj_tower_cake_level_btn)
instance_destroy(obj_tower_cake_card_reward)
obj_player_info_ui.menu_type = 0
obj_world_map_button.world_map = 0
