function material_init(){
	material_registry_init()
	register_material("natural_spices",{"name":"天然香料",
										"description":"天然香料：强化1~6星卡片所需材料",
										"icon":0,
										"pos_x":0,
										"pos_y":0})
	register_material("secret_spices",{"name":"秘制香料",
										"description":"秘制香料：强化7~10星卡片所需材料",
										"icon":1,
										"pos_x":1,
										"pos_y":0})
	register_material("royal_spices",{"name":"皇室香料",
										"description":"皇室香料：强化11~16星卡片所需材料",
										"icon":2,
										"pos_x":2,
										"pos_y":0})
	register_material("clover_1",{"name":"1级四叶草",
										"description":"1级四叶草：将卡片突破至7星所需材料",
										"icon":3,
										"pos_x":0,
										"pos_y":1})
	register_material("clover_2",{"name":"2级四叶草",
										"description":"2级四叶草：将卡片突破至10星所需材料",
										"icon":4,
										"pos_x":1,
										"pos_y":1})
	register_material("clover_3",{"name":"3级四叶草",
										"description":"3级四叶草：将卡片突破至13星所需材料",
										"icon":5,
										"pos_x":2,
										"pos_y":1})
	register_material("less_crystal",{"name":"初级强化水晶",
										"description":"初级强化水晶：强化1~5星宝石所需材料",
										"icon":6,
										"pos_x":0,
										"pos_y":2})
	register_material("middle_crystal",{"name":"中级强化水晶",
										"description":"中级强化水晶：强化6~10星宝石所需材料",
										"icon":7,
										"pos_x":1,
										"pos_y":2})
	register_material("advanced_crystal",{"name":"高级强化水晶",
										"description":"高级强化水晶：强化11~15星宝石所需材料",
										"icon":8,
										"pos_x":2,
										"pos_y":2})
}