function craft_rule_registry_init(){
	global.card_craft_rules = ds_map_create()
	global.gem_craft_rules = ds_map_create()
}

function register_card_craft_rule(target_level,info){
	ds_map_add(global.card_craft_rules,target_level,info)
}

function get_card_craft_rule(target_level){
	return ds_map_find_value(global.card_craft_rules,target_level)
}

function register_gem_craft_rule(target_level,info){
	ds_map_add(global.gem_craft_rules,target_level,info)
}

function get_gem_craft_rule(target_level){
	return ds_map_find_value(global.gem_craft_rules,target_level)
}

function craft_rule_init(){
	craft_rule_registry_init()
	register_card_craft_rule(
		"1",
		{
		"spices_require":"natural_spices",
		"spices_amount":5,
		"clover_require":"none",
		"clover_amount":0,
		"gold_amount":300
		}
	)
	register_card_craft_rule(
		"2",
		{
		"spices_require":"natural_spices",
		"spices_amount":10,
		"clover_require":"none",
		"clover_amount":0,
		"gold_amount":300
		}
	)
	register_card_craft_rule(
		"3",
		{
		"spices_require":"natural_spices",
		"spices_amount":15,
		"clover_require":"none",
		"clover_amount":0,
		"gold_amount":300
		}
	)
	register_card_craft_rule(
		"4",
		{
		"spices_require":"natural_spices",
		"spices_amount":25,
		"clover_require":"none",
		"clover_amount":0,
		"gold_amount":300
		}
	)
	register_card_craft_rule(
		"5",
		{
		"spices_require":"natural_spices",
		"spices_amount":35,
		"clover_require":"none",
		"clover_amount":0,
		"gold_amount":300
		}
	)
	register_card_craft_rule(
		"6",
		{
		"spices_require":"natural_spices",
		"spices_amount":55,
		"clover_require":"none",
		"clover_amount":0,
		"gold_amount":400
		}
	)
	register_card_craft_rule(
		"7",
		{
		"spices_require":"secret_spices",
		"spices_amount":75,
		"clover_require":"clover_1",
		"clover_amount":1,
		"gold_amount":400
		}
	)
	register_card_craft_rule(
		"8",
		{
		"spices_require":"secret_spices",
		"spices_amount":100,
		"clover_require":"none",
		"clover_amount":0,
		"gold_amount":700
		}
	)
	register_card_craft_rule(
		"9",
		{
		"spices_require":"secret_spices",
		"spices_amount":130,
		"clover_require":"none",
		"clover_amount":0,
		"gold_amount":700
		}
	)
	register_card_craft_rule(
		"10",
		{
		"spices_require":"secret_spices",
		"spices_amount":160,
		"clover_require":"clover_2",
		"clover_amount":2,
		"gold_amount":1300
		}
	)
	register_card_craft_rule(
		"11",
		{
		"spices_require":"royal_spices",
		"spices_amount":200,
		"clover_require":"none",
		"clover_amount":0,
		"gold_amount":2600
		}
	)
	register_card_craft_rule(
		"12",
		{
		"spices_require":"royal_spices",
		"spices_amount":245,
		"clover_require":"none",
		"clover_amount":0,
		"gold_amount":2600
		}
	)
	register_card_craft_rule(
		"13",
		{
		"spices_require":"royal_spices",
		"spices_amount":300,
		"clover_require":"clover_3",
		"clover_amount":3,
		"gold_amount":5200
		}
	)
	register_card_craft_rule(
		"14",
		{
		"spices_require":"royal_spices",
		"spices_amount":355,
		"clover_require":"none",
		"clover_amount":0,
		"gold_amount":5200
		}
	)
	register_card_craft_rule(
		"15",
		{
		"spices_require":"royal_spices",
		"spices_amount":420,
		"clover_require":"none",
		"clover_amount":0,
		"gold_amount":10000
		}
	)
	register_card_craft_rule(
		"16",
		{
		"spices_require":"royal_spices",
		"spices_amount":500,
		"clover_require":"none",
		"clover_amount":0,
		"gold_amount":10000
		}
	)
	
	
	register_gem_craft_rule(
		"1",
		{
		"crystal_require":"less_crystal",
		"crystal_amount":5,
		"gold_amount":300
		}
	)
	register_gem_craft_rule(
		"2",
		{
		"crystal_require":"less_crystal",
		"crystal_amount":10,
		"gold_amount":300
		}
	)
	register_gem_craft_rule(
		"3",
		{
		"crystal_require":"less_crystal",
		"crystal_amount":15,
		"gold_amount":300
		}
	)
	register_gem_craft_rule(
		"4",
		{
		"crystal_require":"less_crystal",
		"crystal_amount":25,
		"gold_amount":300
		}
	)
	register_gem_craft_rule(
		"5",
		{
		"crystal_require":"less_crystal",
		"crystal_amount":35,
		"gold_amount":300
		}
	)
	register_gem_craft_rule(
		"6",
		{
		"crystal_require":"middle_crystal",
		"crystal_amount":55,
		"gold_amount":400
		}
	)
	register_gem_craft_rule(
		"7",
		{
		"crystal_require":"middle_crystal",
		"crystal_amount":75,
		"gold_amount":400
		}
	)
	register_gem_craft_rule(
		"8",
		{
		"crystal_require":"middle_crystal",
		"crystal_amount":100,
		"gold_amount":700
		}
	)
	register_gem_craft_rule(
		"9",
		{
		"crystal_require":"middle_crystal",
		"crystal_amount":130,
		"gold_amount":700
		}
	)
	register_gem_craft_rule(
		"10",
		{
		"crystal_require":"middle_crystal",
		"crystal_amount":160,
		"gold_amount":1300
		}
	)
	register_gem_craft_rule(
		"11",
		{
		"crystal_require":"advanced_crystal",
		"crystal_amount":200,
		"gold_amount":2600
		}
	)
	register_gem_craft_rule(
		"12",
		{
		"crystal_require":"advanced_crystal",
		"crystal_amount":245,
		"gold_amount":2600
		}
	)
	register_gem_craft_rule(
		"13",
		{
		"crystal_require":"advanced_crystal",
		"crystal_amount":300,
		"gold_amount":5200
		}
	)
	register_gem_craft_rule(
		"14",
		{
		"crystal_require":"advanced_crystal",
		"crystal_amount":355,
		"gold_amount":5200
		}
	)
	register_gem_craft_rule(
		"15",
		{
		"crystal_require":"advanced_crystal",
		"crystal_amount":420,
		"gold_amount":10000
		}
	)
}