function task_registry_init(){
	global.task_pool = ds_map_create()
}

function register_task(task_id,task_data){
	ds_map_add(global.task_pool,task_id,task_data)
}

function get_task_data(task_id){
	return ds_map_find_value(global.task_pool,task_id)
}

function task_init(){
	task_registry_init()
	{//注册所有主线任务
		register_task("main_level_0",
			{
				"type":"main_task",
				"title":"冒险家的第一战",
				"desc":"从这里开始你的冒险之旅吧。",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_1",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"cookie_island",
						"desc":"通关一次曲奇岛",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"natural_spices",
						"amount":5
					},
					{
						"type":"gold",
						"amount":500
					}
				]
			}
		)
		register_task("main_level_1",
			{
				"type":"main_task",
				"title":"沙拉保卫战",
				"desc":"这里的老鼠怎么这么多？算了，还是沙拉要紧。",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_2",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"salad_island_land",
						"desc":"通关一次色拉岛（陆）",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"natural_spices",
						"amount":5
					},
					{
						"type":"gold",
						"amount":500
					}
				]
			}
		)
		register_task("main_level_2",
			{
				"type":"main_task",
				"title":"水面战争",
				"desc":"是谁在这里放了一个水池？太缺德了！",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_3",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"salad_island_water",
						"desc":"通关一次色拉岛（水）",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"natural_spices",
						"amount":5
					},
					{
						"type":"gold",
						"amount":500
					}
				]
			}
		)
		register_task("main_level_3",
			{
				"type":"main_task",
				"title":"夜间保卫战",
				"desc":"好黑……居然连天上掉的火苗都没有了！",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_4",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"mousse_island",
						"desc":"通关一次慕斯岛",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"natural_spices",
						"amount":10
					},
					{
						"type":"gold",
						"amount":750
					}
				]
			}
		)
		register_task("main_level_4",
			{
				"type":"main_task",
				"title":"巧克力防线",
				"desc":"老鼠越来越多了，是时候让我们的高个子朋友来帮忙了。",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_5",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"champagne_island_land",
						"desc":"通关一次香槟岛（陆）",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"natural_spices",
						"amount":10
					},
					{
						"type":"gold",
						"amount":750
					}
				]
			}
		)
		register_task("main_level_5",
			{
				"type":"main_task",
				"title":"夜间水战",
				"desc":"为什么青蛙王子要骑着自己曾经的同类？真是令人不解。",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_6",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"champagne_island_water",
						"desc":"通关一次香槟岛（水）",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"natural_spices",
						"amount":10
					},
					{
						"type":"gold",
						"amount":750
					}
				]
			}
		)
		register_task("main_level_6",
			{
				"type":"main_task",
				"title":"探秘神殿",
				"desc":"隐秘的神殿深处，供奉的又是何方神圣？",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_7",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"temple",
						"desc":"通关一次神殿",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"natural_spices",
						"amount":20
					},
					{
						"type":"gold",
						"amount":1500
					}
				]
			}
		)
		register_task("main_level_7",
			{
				"type":"main_task",
				"title":"堵洞行动",
				"desc":"真是太离谱了！它们居然把老鼠洞打到野餐布上来了！",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_8",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"pudding_island_daytime",
						"desc":"通关一次布丁岛（日）",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"natural_spices",
						"amount":15
					},
					{
						"type":"gold",
						"amount":1000
					}
				]
			}
		)
		register_task("main_level_8",
			{
				"type":"main_task",
				"title":"夜间野餐",
				"desc":"鼹鼠是干什么的？应该是挖鼠夹的吧",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_9",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"pudding_island_night",
						"desc":"通关一次布丁岛（夜）",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"natural_spices",
						"amount":15
					},
					{
						"type":"gold",
						"amount":1000
					}
				]
			}
		)
		register_task("main_level_9",
			{
				"type":"main_task",
				"title":"双水道战争",
				"desc":"这里就是传说中的反转泳池吗？",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_10",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"cocoa_island_daytime",
						"desc":"通关一次可可岛（日）",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"natural_spices",
						"amount":15
					},
					{
						"type":"gold",
						"amount":1000
					}
				]
			}
		)
		register_task("main_level_10",
			{
				"type":"main_task",
				"title":"大战蝙蝠侠",
				"desc":"蝙蝠侠没见到，倒是见到小偷了……",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_11",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"cocoa_island_night",
						"desc":"通关一次可可岛（夜）",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"natural_spices",
						"amount":20
					},
					{
						"type":"gold",
						"amount":1250
					}
				]
			}
		)
		register_task("main_level_11",
			{
				"type":"main_task",
				"title":"大雾退散",
				"desc":"退！退！退！",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_12",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"curry_island_daytime",
						"desc":"通关一次咖喱岛（日）",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"natural_spices",
						"amount":20
					},
					{
						"type":"gold",
						"amount":1250
					}
				]
			}
		)
		register_task("main_level_12",
			{
				"type":"main_task",
				"title":"垃圾处理",
				"desc":"可可岛（雾水）",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_13",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"curry_island_night",
						"desc":"通关一次咖喱岛（夜）",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"natural_spices",
						"amount":20
					},
					{
						"type":"gold",
						"amount":1250
					}
				]
			}
		)
		register_task("main_level_13",
			{
				"type":"main_task",
				"title":"决战深渊",
				"desc":"这里就是最后一关了吗？也不过如此吧。",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_14",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"abyss",
						"desc":"通关一次深渊岛",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"natural_spices",
						"amount":40
					},
					{
						"type":"gold",
						"amount":2500
					}
				]
			}
		)
		register_task("main_level_14",
			{
				"type":"main_task",
				"title":"洗碗池战争",
				"desc":"为什么一个洗碗池的BGM会这么燃？",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"main_level_15",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"mustard_room_daytime",
						"desc":"通关一次芥末小屋（日）",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"secret_spices",
						"amount":25
					},
					{
						"type":"gold",
						"amount":1500
					}
				]
			}
		)
	}
	{//注册所有支线任务
		register_task("card_upgrade_1",
			{
				"type":"side_task",
				"title":"增强实力-1",
				"desc":"只有拥有更高级的卡片才能抵御越来越多的敌人。",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"card_upgrade_2",
				"requirements":[
					{
						"type":"card_upgrade",
						"target_card_level":1,
						"desc":"将一张卡片强化至1星",
						"require":1,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"natural_spices",
						"amount":5
					},
					{
						"type":"gold",
						"amount":500
					}
				]
			}
		)
		register_task("card_upgrade_2",
			{
				"type":"side_task",
				"title":"增强实力-2",
				"desc":"只有拥有更高级的卡片才能抵御越来越多的敌人。",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"card_upgrade_3",
				"requirements":[
					{
						"type":"card_upgrade",
						"target_card_level":2,
						"desc":"将5张卡片强化至2星",
						"require":5,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"natural_spices",
						"amount":20
					},
					{
						"type":"gold",
						"amount":1000
					}
				]
			}
		)
		register_task("card_upgrade_3",
			{
				"type":"side_task",
				"title":"增强实力-3",
				"desc":"只有拥有更高级的卡片才能抵御越来越多的敌人。",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"card_upgrade_4",
				"requirements":[
					{
						"type":"card_upgrade",
						"target_card_level":4,
						"desc":"将3张卡片强化至4星",
						"require":3,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"natural_spices",
						"amount":25
					},
					{
						"type":"gold",
						"amount":2000
					}
				]
			}
		)
		register_task("card_upgrade_4",
			{
				"type":"side_task",
				"title":"增强实力-4",
				"desc":"只有拥有更高级的卡片才能抵御越来越多的敌人。",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"card_upgrade_5",
				"requirements":[
					{
						"type":"card_upgrade",
						"target_card_level":6,
						"desc":"将5张卡片强化至6星",
						"require":5,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"natural_spices",
						"amount":50
					},
					{
						"type":"gold",
						"amount":2500
					}
				]
			}
		)
		register_task("card_upgrade_5",
			{
				"type":"side_task",
				"title":"增强实力-5",
				"desc":"只有拥有更高级的卡片才能抵御越来越多的敌人。",
				"single_game":false,//非单局完成
				"oneshot":false,//非一命完成
				"task_unlock":"card_upgrade_6",
				"requirements":[
					{
						"type":"card_upgrade",
						"target_card_level":20,
						"desc":"请等待后续开放更高星级",
						"require":5,
					}
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"secret_spices",
						"amount":75
					},
					{
						"type":"gold",
						"amount":3500
					}
				]
			}
		)
	}
	{//注册所有挑战任务
		register_task("flame_save_1",
			{
				"type":"challenge_task",
				"title":"神殿节约之旅",
				"desc":"冒险途中突发状况很多，需要积攒火苗才能及时应对。",
				"single_game":true,//仅限单局游戏内完成
				"oneshot":false,//非一命任务
				"task_unlock":"flame_save_2",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"temple",
						"desc":"通关一次神殿",
						"require":1,
					},
					{
						"type":"flame_left",
						"desc":"关卡结算时，剩余3500以上的火苗",
						"require":3500,
					},
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"natural_spices",
						"amount":20
					},
					{
						"type":"gold",
						"amount":1000
					}
				]
			}
		)
		register_task("flame_save_2",
			{
				"type":"challenge_task",
				"title":"深渊节约之旅",
				"desc":"冒险途中突发状况很多，需要积攒火苗才能及时应对。",
				"single_game":true,//仅限单局游戏内完成
				"oneshot":false,//非一命任务
				"task_unlock":"flame_save_3",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"abyss",
						"desc":"通关一次深渊",
						"require":1,
					},
					{
						"type":"flame_left",
						"desc":"关卡结算时，剩余5000以上的火苗",
						"require":5000,
					},
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"natural_spices",
						"amount":50
					},
					{
						"type":"gold",
						"amount":5000
					}
				]
			}
		)
		register_task("flame_save_3",
			{
				"type":"challenge_task",
				"title":"芝士城堡节约之旅",
				"desc":"冒险途中突发状况很多，需要积攒火苗才能及时应对。",
				"single_game":true,//仅限单局游戏内完成
				"oneshot":false,//非一命任务
				"task_unlock":"flame_save_4",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"cheese_castle",
						"desc":"通关一次芝士城堡",
						"require":1,
					},
					{
						"type":"flame_left",
						"desc":"关卡结算时，剩余6000以上的火苗",
						"require":6000,
					},
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"secret_spices",
						"amount":75
					},
					{
						"type":"gold",
						"amount":7500
					}
				]
			}
		)
		register_task("perfect_challenge_1",
			{
				"type":"challenge_task",
				"title":"完美挑战-1",
				"desc":"在限定条件下通关指定关卡，证明你的实力。",
				"single_game":true,//仅限单局游戏内完成
				"oneshot":false,//非一命任务
				"task_unlock":"perfect_challenge_2",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"temple",
						"desc":"通关一次神殿",
						"require":1,
					},
					{
						"type":"cat_loss",
						"desc":"不得失去任何猫",
						"require":0,
					},
					{
						"type":"card_loss",
						"desc":"不得损失超过20张卡片",
						"require":20,
					},
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"natural_spices",
						"amount":30
					},
					{
						"type":"gold",
						"amount":2000
					},
					{
						"type":"item",
						"item_id":"clover_1",
						"amount":1
					},
				]
			}
		)
		register_task("perfect_challenge_2",
			{
				"type":"challenge_task",
				"title":"完美挑战-2",
				"desc":"在限定条件下通关指定关卡，证明你的实力。",
				"single_game":true,//仅限单局游戏内完成
				"oneshot":false,//非一命任务
				"task_unlock":"perfect_challenge_3",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"abyss",
						"desc":"通关一次深渊",
						"require":1,
					},
					{
						"type":"cat_loss",
						"desc":"不得失去任何猫",
						"require":0,
					},
					{
						"type":"card_loss",
						"desc":"不得损失超过35张卡片",
						"require":35,
					},
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"natural_spices",
						"amount":65
					},
					{
						"type":"gold",
						"amount":5000
					},
					{
						"type":"item",
						"item_id":"clover_1",
						"amount":1
					},
				]
			}
		)
		register_task("perfect_challenge_3",
			{
				"type":"challenge_task",
				"title":"完美挑战-3",
				"desc":"在限定条件下通关指定关卡，证明你的实力。",
				"single_game":true,//仅限单局游戏内完成
				"oneshot":false,//非一命任务
				"task_unlock":"perfect_challenge_4",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"cheese_castle",
						"desc":"通关一次芝士城堡",
						"require":1,
					},
					{
						"type":"cat_loss",
						"desc":"不得失去任何猫",
						"require":0,
					},
					{
						"type":"card_loss",
						"desc":"不得损失超过30张卡片",
						"require":30,
					},
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"secret_spices",
						"amount":80
					},
					{
						"type":"gold",
						"amount":10000
					},
					{
						"type":"item",
						"item_id":"clover_1",
						"amount":2
					},
				]
			}
		)
		register_task("hardcore_challenge_1",
			{
				"type":"challenge_task",
				"title":"极限挑战-1",
				"desc":"你能在缺少输出的情况下完成关卡吗？",
				"single_game":true,//仅限单局游戏内完成
				"oneshot":false,//非一命任务
				"task_unlock":"hardcore_challenge_2",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"temple",
						"desc":"通关一次神殿",
						"require":1,
					},
					{
						"type":"weapon_limit",
						"desc":"不能装备任何武器和宝石",
						"require":1,
					},
					{
						"type":"card_type_limit",
						"desc":"不能携带任何炸弹类卡片（包括冰桶炸弹）",
						"limit_card_type":"bomb",
						"require":1,
					},
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"natural_spices",
						"amount":30
					},
					{
						"type":"gold",
						"amount":2500
					}
				]
			}
		)
		register_task("hardcore_challenge_2",
			{
				"type":"challenge_task",
				"title":"极限挑战-2",
				"desc":"你能在缺少输出的情况下完成关卡吗？",
				"single_game":true,//仅限单局游戏内完成
				"oneshot":false,//非一命任务
				"task_unlock":"hardcore_challenge_3",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"abyss",
						"desc":"通关一次深渊",
						"require":1,
					},
					{
						"type":"weapon_limit",
						"desc":"不能装备任何武器和宝石",
						"require":1,
					},
					{
						"type":"card_type_limit",
						"desc":"不能携带任何炸弹类卡片（包括冰桶炸弹）",
						"limit_card_type":"bomb",
						"require":1,
					},
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"natural_spices",
						"amount":65
					},
					{
						"type":"gold",
						"amount":7500
					}
				]
			}
		)
		register_task("hardcore_challenge_3",
			{
				"type":"challenge_task",
				"title":"极限挑战-3",
				"desc":"你能在缺少输出的情况下完成关卡吗？",
				"single_game":true,//仅限单局游戏内完成
				"oneshot":false,//非一命任务
				"task_unlock":"hardcore_challenge_4",
				"requirements":[
					{
						"type":"level_complete",
						"target_level":"cheese_castle",
						"desc":"通关一次芝士城堡",
						"require":1,
					},
					{
						"type":"weapon_limit",
						"desc":"不能装备任何武器和宝石",
						"require":1,
					},
					{
						"type":"card_type_limit",
						"desc":"不能携带任何炸弹类卡片（包括冰桶炸弹）",
						"limit_card_type":"bomb",
						"require":1,
					},
				],
				"rewards":[
					{
						"type":"item",
						"item_id":"secret_spices",
						"amount":80
					},
					{
						"type":"gold",
						"amount":10000
					},
					{
						"type":"item",
						"item_id":"clover_1",
						"amount":1
					},
				]
			}
		)
	}
}